---
repos:
  -
    hooks:
      -
        id: flake8
      -
        id: trailing-whitespace
      -
        id: end-of-file-fixer
      -
        id: check-yaml
      -
        id: check-added-large-files
    repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.4.0
  -
    hooks:
      -
        id: black
    repo: "https://github.com/ambv/black"
    rev: stable
  -
    hooks:
      -
        always_run: true
        entry: pytest
        id: pytest-check
        language: system
        name: pytest-check
        pass_filenames: false
    repo: local
